apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: at-kibana
        image: docker.elastic.co/kibana/kibana:7.0.1
        ports:
        - containerPort: 5601