apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "labeltemplate" .Values.labels | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "labeltemplate" .Values.labels | indent 8 }}
    spec:
      containers:
      - name: {{ .Values.image.containerName }}
        image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        resources:
          limits:
            memory: "64Mi"
            cpu: "1000m"
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: {{ .Values.image.secret }}