apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:  
  selector:
    {{- include "labeltemplate" .Values.labels | indent 4 }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP