{
 "title": "Used Resources",
 "description": "Dashboard to show the resource requests vs allocatable in the cluster",
 "tags": [
  "kubernetes",
  "k8s",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_namespace_labels, namespace)"
   },
   {
    "name": "app",
    "label": "container",
    "query": "label_values(kube_pod_container_info{namespace=\"$namespace\"}, container)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(kube_node_info, node)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Wide", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory",
   "type": "graph",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "kbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable{resource=\"memory\"} / 1024 ) by (instance))",
     "legendFormat": "Allocatable Memory"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{resource=\"memory\"} / 1024 ) by (exported_pod)\n * on (exported_pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (exported_pod) == 1)\n )",
     "legendFormat": "Requested Memory"
    },
    {
     "expr": "min(sum(kube_node_status_capacity_memory_bytes / 1024 ) by (instance))",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum(kube_metrics_server_pods_mem)",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 5, "x": 7, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n   kube_metrics_server_pods_mem  * 1024\n ) / sum(kube_node_status_allocatable{resource=\"memory\"}) * 100"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 1 },
   "format": "kbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_metrics_server_pods_mem)"
    }
   ]
  },
  {
   "title": "Allocatable Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Requested Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{resource=\"memory\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)\n )"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_cpu_cores) by (instance))",
     "legendFormat": "Allocatable CPU Cores"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance))",
     "legendFormat": "Requested CPU Cores"
    },
    {
     "expr": "(sum(kube_metrics_server_pods_cpu) / 1000000000 )",
     "legendFormat": "Used CPU Cores"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 5, "x": 7, "y": 11 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(kube_metrics_server_pods_cpu) / 1000000000 )\n/ sum(kube_node_status_allocatable_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "Used CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_metrics_server_pods_cpu) / 1000000000"
    }
   ]
  },
  {
   "title": "Allocatable CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "Requested CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)\n )"
    }
   ]
  },
  {
   "title": "Requests/Limit/Usage by Namespace",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{namespace=~\".*\", resource=\"memory\"}) by (namespace, exported_pod)\n * on (namespace, exported_pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=~\".*\"}) by (namespace, exported_pod) == 1)\n ) by (namespace)",
     "legendFormat": "Requested Memory"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_limits{namespace=~\".*\", resource=\"memory\"}) by (namespace, exported_pod)\n * on (namespace, exported_pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=~\".*\"}) by (namespace, exported_pod) == 1)\n ) by (namespace)",
     "legendFormat": "Limit Memory"
    },
    {
     "expr": "label_replace(sum(kube_metrics_server_pods_mem) by (pod_namespace), \"namespace\", \"$1\", \"pod_namespace\", \"(.*)\")",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "(sum(sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (namespace, exported_pod)* on (namespace, exported_pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (namespace, exported_pod) == 1)) by (namespace))\n-\n(sum(label_replace(sum(kube_metrics_server_pods_mem) by (pod_namespace), \"namespace\", \"$1\", \"pod_namespace\", \"(.*)\")) by (namespace) * 1024)",
     "legendFormat": "Wasted Memory"
    },
    {
     "expr": "((100 * \n(sum(label_replace(sum(kube_metrics_server_pods_mem) by (pod_namespace), \"namespace\", \"$1\", \"pod_namespace\", \"(.*)\")) by (namespace) * 1024)\n/ \nsum(sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (namespace, exported_pod)* on (namespace, exported_pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (namespace, exported_pod) == 1)) by (namespace)\n- 100) * -1)",
     "legendFormat": "Wasted Memory %"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{namespace=~\".*\", resource=\"cpu\"}) by (namespace, exported_pod)\n * on (namespace, exported_pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=~\".*\"}) by (namespace, exported_pod) == 1)\n ) by (namespace)",
     "legendFormat": "Requested CPU"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_limits{namespace=~\".*\", resource=\"cpu\"}) by (namespace, exported_pod)\n * on (namespace, exported_pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (namespace, exported_pod) == 1)\n ) by (namespace)",
     "legendFormat": "Limit CPU"
    },
    {
     "expr": "label_replace(sum(kube_metrics_server_pods_cpu) by (pod_namespace) / 1000000000 , \"namespace\", \"$1\", \"pod_namespace\", \"(.*)\")",
     "legendFormat": "Used CPU"
    },
    {
     "expr": "(sum(sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (namespace, exported_pod)* on (namespace, exported_pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (namespace, exported_pod) == 1)) by (namespace))\n-\n(sum(label_replace(sum(kube_metrics_server_pods_cpu) by (pod_namespace) / 1000000000 , \"namespace\", \"$1\", \"pod_namespace\", \"(.*)\")) by (namespace))",
     "legendFormat": "Wasted CPU"
    },
    {
     "expr": "((100 * \n(sum(label_replace(sum(kube_metrics_server_pods_cpu) by (pod_namespace) / 1000000000 , \"namespace\", \"$1\", \"pod_namespace\", \"(.*)\")) by (namespace))\n/ \nsum(sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (namespace, exported_pod)* on (namespace, exported_pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (namespace, exported_pod) == 1)) by (namespace)\n- 100) * -1)",
     "legendFormat": "Wasted CPU %"
    }
   ]
  },
  { "title": "Resource by Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Memory",
   "type": "graph",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "kbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"}) by (exported_pod)\n * on (exported_pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$namespace\"}) by (exported_pod) == 1)\n ) / 1000",
     "legendFormat": "Requested Memory"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"}) by (exported_pod)\n * on (exported_pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$namespace\"}) by (exported_pod) == 1)\n ) / 1000",
     "legendFormat": "Limit Memory"
    },
    {
     "expr": "sum(kube_metrics_server_pods_mem{pod_namespace=\"$namespace\"})",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": "Limit Memory",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 31 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\nsum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"}) by (exported_pod)\n * on (exported_pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$namespace\"}) by (exported_pod) == 1)\n )"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 31 },
   "format": "kbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_metrics_server_pods_mem{pod_namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_metrics_server_pods_cpu{pod_namespace=\"$namespace\"}) / 1000000000",
     "legendFormat": "Used CPU"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"}) by (exported_pod)\n * on (exported_pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$namespace\"}) by (exported_pod) == 1)\n )",
     "legendFormat": "Requested CPU"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"}) by (exported_pod)\n * on (exported_pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$namespace\"}) by (exported_pod) == 1)\n )",
     "legendFormat": "Limit CPU"
    }
   ]
  },
  {
   "title": "Limit CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 40 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\nsum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"}) by (exported_pod)\n * on (exported_pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$namespace\"}) by (exported_pod) == 1)\n )"
    }
   ]
  },
  {
   "title": "Used CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 40 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_metrics_server_pods_cpu{pod_namespace=\"$namespace\"}) / 1000000000"
    }
   ]
  },
  {
   "title": "Memory Request/Limit by Pod",
   "type": "table",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"}) by (exported_pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"})  by (exported_pod)"
    },
    {
     "expr": "label_replace(sum(kube_metrics_server_pods_mem{pod_namespace=~\"$namespace\"}) by (pod_name), \"exported_pod\", \"$1\", \"pod_name\", \"(.*)\")"
    },
    {
     "expr": "((100 * \n(sum(label_replace(sum(kube_metrics_server_pods_mem{pod_namespace=~\"$namespace\"}) by (pod_name), \"exported_pod\", \"$1\", \"pod_name\", \"(.*)\")) by (exported_pod) * 1024)\n/ \nsum(sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"$namespace\"}) by (exported_pod)* on (exported_pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (exported_pod) == 1)) by (exported_pod)\n- 100) * -1)",
     "legendFormat": "Wasted Live %"
    }
   ]
  },
  {
   "title": "CPU Request/Limit by Pod",
   "type": "table",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 49 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"$namespace\"}) by (exported_pod)* on (exported_pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (exported_pod) == 1)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=~\"$namespace\"}) by (exported_pod)* on (exported_pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (exported_pod) == 1)"
    },
    {
     "expr": "label_replace(sum(kube_metrics_server_pods_cpu{pod_namespace=~\"$namespace\"}) by (pod_name) / 1000000000 , \"exported_pod\", \"$1\", \"pod_name\", \"(.*)\") "
    },
    {
     "expr": "((100 * \n(sum(label_replace(sum(kube_metrics_server_pods_cpu{pod_namespace=~\"$namespace\"}) by (pod_name), \"exported_pod\", \"$1\", \"pod_name\", \"(.*)\")) by (exported_pod) / 1000000000)\n/ \nsum(sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"$namespace\"}) by (exported_pod)* on (exported_pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (exported_pod) == 1)) by (exported_pod)\n- 100) * -1)",
     "legendFormat": "Wasted CPU %"
    }
   ]
  },
  { "title": "Resource by app", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Memory by app",
   "type": "graph",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "kbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\",container=\"$app\"})/ 1024",
     "legendFormat": "Requested Memory $app"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", container=\"$app\"}) / 1024",
     "legendFormat": "Limit Memory $app"
    },
    {
     "expr": "sum(kube_metrics_server_pods_mem{pod_namespace=\"$namespace\", pod_container_name=~\"$app\"})",
     "legendFormat": "Used Memory $app"
    }
   ]
  },
  {
   "title": "CPU Cores by app",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\", container=\"$app\"})",
     "legendFormat": "Requested CPU $app"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\", container=\"$app\"})",
     "legendFormat": "Limit CPU $app"
    },
    {
     "expr": "sum(kube_metrics_server_pods_cpu{pod_namespace=\"$namespace\", pod_container_name=\"$app\"}) / 1000000000",
     "legendFormat": "Used CPU $app"
    }
   ]
  },
  {
   "title": "Memory by pod",
   "type": "graph",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "kbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\",container=\"$app\"}) by (pod) / 1024",
     "legendFormat": "Requested Memory {{exported_pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", container=\"$app\"})  by (pod) / 1024",
     "legendFormat": "Limit Memory {{exported_pod}}"
    },
    {
     "expr": "sum(kube_metrics_server_pods_mem{pod_namespace=\"$namespace\", pod_container_name=\"$app\"})  by (pod_name)",
     "legendFormat": "Used Memory {{pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Cores by pod",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\",container=\"$app\"}) by (pod)",
     "legendFormat": "Requested CPU {{exported_pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\", container=\"$app\"}) by (pod)",
     "legendFormat": "Limit CPU {{exported_pod}}"
    },
    {
     "expr": "sum(kube_metrics_server_pods_cpu{pod_namespace=\"$namespace\", pod_container_name=\"$app\"}) by (pod_name) / 1000000000",
     "legendFormat": "Used CPU {{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Request/Limit by Pod",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", container=~\"$app\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\",container=~\"$app\"}) by (pod)"
    },
    {
     "expr": "label_replace(sum(kube_metrics_server_pods_mem{pod_namespace=~\"$namespace\",pod_container_name=~\"$app\"}) by (pod_name), \"exported_pod\", \"$1\", \"pod_name\", \"(.*)\")"
    },
    {
     "expr": "label_replace(sum(avg_over_time(kube_metrics_server_pods_mem{pod_namespace=~\"$namespace\",pod_container_name=~\"$app\"}[1d])) by (pod_name), \"exported_pod\", \"$1\", \"pod_name\", \"(.*)\")"
    },
    {
     "expr": "label_replace(sum(avg_over_time(kube_metrics_server_pods_mem{pod_namespace=~\"$namespace\",pod_container_name=~\"$app\"}[2d])) by (pod_name), \"exported_pod\", \"$1\", \"pod_name\", \"(.*)\")"
    },
    {
     "expr": "label_replace(sum(max_over_time(kube_metrics_server_pods_mem{pod_namespace=~\"$namespace\",pod_container_name=~\"$app\"}[2d])) by (pod_name), \"exported_pod\", \"$1\", \"pod_name\", \"(.*)\")"
    }
   ]
  },
  {
   "title": "CPU Request/Limit by Pod",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\",container=~\"$app\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\",container=~\"$app\"}) by (pod)"
    },
    {
     "expr": "label_replace(sum(kube_metrics_server_pods_cpu{pod_namespace=~\"$namespace\",pod_container_name=~\"$app\"}) by (pod_name) / 1000000000 , \"exported_pod\", \"$1\", \"pod_name\", \"(.*)\") "
    },
    {
     "expr": "label_replace(sum(avg_over_time(kube_metrics_server_pods_cpu{pod_namespace=~\"$namespace\",pod_container_name=~\"$app\"}[1d])) by (pod_name) / 1000000000, \"exported_pod\", \"$1\", \"pod_name\", \"(.*)\")"
    },
    {
     "expr": "label_replace(sum(avg_over_time(kube_metrics_server_pods_cpu{pod_namespace=~\"$namespace\",pod_container_name=~\"$app\"}[2d])) by (pod_name) / 1000000000, \"exported_pod\", \"$1\", \"pod_name\", \"(.*)\")"
    },
    {
     "expr": "label_replace(sum(max_over_time(kube_metrics_server_pods_cpu{pod_namespace=~\"$namespace\",pod_container_name=~\"$app\"}[2d])) by (pod_name) / 1000000000, \"exported_pod\", \"$1\", \"pod_name\", \"(.*)\")"
    }
   ]
  },
  { "title": "Resource by Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Nodes Allocatable vs Usage",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\"}) by (node)"
    },
    {
     "expr": "label_replace(sum(kube_metrics_server_nodes_mem) by (exported_instance), \"node\", \"$1\", \"exported_instance\", \"(.*)\") "
    }
   ]
  },
  {
   "title": "CPU Allocatable vs Usage",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"}) by (node)"
    },
    {
     "expr": "label_replace(sum(kube_metrics_server_nodes_cpu) by (exported_instance) / 1000000000 , \"node\", \"$1\", \"exported_instance\", \"(.*)\") "
    }
   ]
  },
  {
   "title": "CPU / Memory Allocatable vs Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "decbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", node=~\"$instance\"}) by (node)",
     "legendFormat": "Memory Allocatable: {{node}}"
    },
    {
     "expr": "sum(kube_metrics_server_nodes_mem{instance=~\"$instance\"}) by (instance) * 1024",
     "legendFormat": "Memory Utilization: {{instance}}"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", node=~\"$instance\"}) by (node)",
     "legendFormat": "CPU Allocatable: {{node}}"
    },
    {
     "expr": "sum(kube_metrics_server_nodes_cpu{instance=~\"$instance\"}) by (instance) / 1000000000 ",
     "legendFormat": "CPU Utilization: {{instance}}"
    }
   ]
  }
 ]
}