apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonLabels:
  app.kubernetes.io/name: prometheus
  app.kubernetes.io/part-of: monitoring
resources:
- namespace.yaml
- role.yaml
- service-account.yaml
- role-binding.yaml
- persistent-volume.yaml
- deployment.yaml
- service.yaml
images:
- name: prom/prometheus
  newTag: v2.3.2
configMapGenerator:
- name: prometheus-configuration
  files:
  - prometheus.yaml
