apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "labeltemplate" .Values.labels | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "labeltemplate" .Values.labels | indent 8 }}
    spec:
      containers:
      - name: {{ .Values.image.containerName }}
        image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        resources:
          limits:
            memory: "150Mi"
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SEQ_CACHE_SYSTEMRAMTARGET 
          value: "0.1"
        volumeMounts:
          - mountPath: "/data"
            name: seqdata
        ports:
        - name: ingestion
          containerPort: 5341
          protocol: TCP
        - name: ui
          containerPort: 80
          protocol: TCP
      volumes:
        - name: seqdata
          persistentVolumeClaim:
            claimName: seq-data