apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:  
  type: ClusterIP
  selector:
    {{- include "labeltemplate" .Values.labels | indent 4 }}
  ports:   
    - port: 5341
      protocol: TCP
      name: ingestion
    - port: 80
      protocol: TCP
      name: ui