apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: air-team-api
  template:
    metadata:
      labels:
        app: air-team-api
    spec:
      containers:
      - name: at-api-instance
        image: docker.pkg.github.com/hvojdani/air-team/air-team-api:0.34.0
        resources:
          limits:
            memory: "150Mi"
        ports:
        - containerPort: 80