apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - host: airimagefind.com
    http:
      paths:
      - path: /v1/
        backend:
          serviceName: apibackend
          servicePort: 80
      - path: /swagger/
        backend:
          serviceName: apibackend
          servicePort: 80
      - path: /
        backend:
          serviceName: uiapp
          servicePort: 80