apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: air-team-ui
  template:
    metadata:
      labels:
        app: air-team-ui
    spec:
      containers:
      - name: at-ui-instance
        image: ghcr.io/hvojdani/air-team-ui:3.2
        resources:
          limits:
            memory: "64Mi"
            cpu: "1000m"
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred