apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq-deploy
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: seq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: seq
    spec:
      containers:
      - name: seq-instance
        image: datalust/seq:2021.2
        resources:
          limits:
            memory: "150Mi"
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SEQ_CACHE_SYSTEMRAMTARGET 
          value: "0.1"
        volumeMounts:
          - mountPath: "/data"
            name: seqdata
        ports:
        - name: ingestion
          containerPort: 5341
          protocol: TCP
        - name: ui
          containerPort: 80
          protocol: TCP
      volumes:
        - name: seqdata
          persistentVolumeClaim:
            claimName: seqpvc