apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "labeltemplate" .Values.labels | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "labeltemplate" .Values.labels | indent 8 }}
    spec:
      containers:
      - name: {{ .Values.image.containerName }}
        image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        resources:
          limits:
            memory: "100Mi"
            cpu: "2000m"
        volumeMounts:
          - mountPath: "/data"
            name: redisdata
        ports:
        - containerPort: 6379
      volumes:
        - name: redisdata
          persistentVolumeClaim:
            claimName: redispvc