name: .NET Core CI

on:
  push:
    paths:
      - Backend/**
    branches: [ master ]
  pull_request:
    paths:
      - Backend/**
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Build with dotnet
      run: dotnet build ./Backend/AirTeamApi/AirTeamApi.csproj --configuration Release
    - name: Test with dotnet
      run: dotnet test ./Backend/AirTeamApi.Tests/AirTeamApi.Tests.csproj
