# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    paths:
      - UI/**
    branches: [ master ]
  pull_request:
    paths:
      - UI/**
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      
    - run: cd UI/
      working-directory: ./UI  
    - run: npm ci
      working-directory: ./UI  
    - run: npm run build
      working-directory: ./UI  
    - run: npm test
      working-directory: ./UI  
      env:
        CI: true
